
//
// NSDate_DateFormat.ext.swift
//
// Code autogenerated. Do not modify this file.
//

import Foundation

// For receive and send dates in JSONs
let DefaultDateFormat: String = "yyyy-MM-dd'T'HH:mm:ss.SSS"
extension NSDate
{
	static func initFromString (dateString: String?, withDateFormat dateFormat: String = DefaultDateFormat) -> NSDate?
	{
		if (dateString == nil) { return nil; }
		
		let formatter = NSDateFormatter()
		formatter.dateFormat = dateFormat;
		return formatter.dateFromString(dateString!);
	}
	
	func toString (withDateFormat dateFormat: String = DefaultDateFormat) -> String
	{
		let dateFormatter = NSDateFormatter();
		dateFormatter.dateFormat = dateFormat;
		return dateFormatter.stringFromDate(self);
	}
}

