	
		//
		// CompetitionDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class CompetitionDTO 	    {
		 
				var id: Int?;
				    	 
		 
				var name: String?;
				    	 
		 
				var event_: [Event_DTO]?;
				    	 
		 
				var sport_oid: Int?;
				    	 
		 
				var place: String?;
				    	 
		 
				var team_oid: [Int]?;
				    	 
		 
				var clubs: Bool?;
				    	 
		 
				var season_oid: [Int]?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


				
					dictionary["id"] = self.id;
				

				
					dictionary["name"] = self.name;
				

					dictionary["event_"] = NSNull();
					if (self.event_ != nil)
					{
						var arrayOfDictionary: [[String : AnyObject]] = [];
						for item in self.event_!
						{
							arrayOfDictionary.append(item.toDictionary());
						}
						
						dictionary["event_"] = arrayOfDictionary;
					}
			

					dictionary["sport_oid"] = self.sport_oid;
			

				
					dictionary["place"] = self.place;
				

					dictionary["team_oid"] = self.team_oid;
			

				
					dictionary["clubs"] = self.clubs;
				

					dictionary["season_oid"] = self.season_oid;
			
						
				return dictionary;
			}
		}
		
	