	
		//
		// CorrectScoreDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class CorrectScoreDTO :    		PickDTO
	    {
		 
				var homeScore: Int?;
				    	 
		 
				var awayScore: Int?;
				    	 
	   	   
			// MARK: - Constructor
			
			
			override init ()
			{
				super.init();
			}
			override func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
				dictionary = super.toDictionary();
			


				
					dictionary["homeScore"] = self.homeScore;
				

				
					dictionary["awayScore"] = self.awayScore;
				
						
				return dictionary;
			}
		}
		
	