	
		//
		// DoubleChanceDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class DoubleChanceDTO :    		ResultDTO
	    {
		 
				var result_b: Result?;
				    	 
	   	   
			// MARK: - Constructor
			
			
			override init ()
			{
				super.init();
			}
			override func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
				dictionary = super.toDictionary();
			


				
					dictionary["result_b"] = self.result_b?.rawValue;
				
						
				return dictionary;
			}
		}
		
	