	
		//
		// GoalDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class GoalDTO :    		PickDTO
	    {
		 
				var line: Line?;
				    	 
		 
				var quantity: Double?;
				    	 
		 
				var asian: Bool?;
				    	 
	   	   
			// MARK: - Constructor
			
			
			override init ()
			{
				super.init();
			}
			override func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
				dictionary = super.toDictionary();
			


				
					dictionary["line"] = self.line?.rawValue;
				

				
					dictionary["quantity"] = self.quantity;
				

				
					dictionary["asian"] = self.asian;
				
						
				return dictionary;
			}
		}
		
	