	
		//
		// HandicapDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class HandicapDTO :    		GoalDTO
	    {
		 
				var result: Result?;
				    	 
	   	   
			// MARK: - Constructor
			
			
			override init ()
			{
				super.init();
			}
			override func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
				dictionary = super.toDictionary();
			


				
					dictionary["result"] = self.result?.rawValue;
				
						
				return dictionary;
			}
		}
		
	