	
		//
		// LoginDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class LoginDTO 	    {
		 
				var id: Int?;
				    	 
		 
				var alias: String?;
				    	 
		 
				var date: NSDate?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


				
					dictionary["id"] = self.id;
				

				
					dictionary["alias"] = self.alias;
				

				
					dictionary["date"] = self.date?.toString();
				
						
				return dictionary;
			}
		}
		
	