	
		//
		// MatchDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class MatchDTO :    		Event_DTO
	    {
		 
				var away_oid: Int?;
				    	 
		 
				var home_oid: Int?;
				    	 
		 
				var stadium: String?;
				    	 
	   	   
			// MARK: - Constructor
			
			
			override init ()
			{
				super.init();
			}
			override func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
				dictionary = super.toDictionary();
			


					dictionary["away_oid"] = self.away_oid;
			

					dictionary["home_oid"] = self.home_oid;
			

				
					dictionary["stadium"] = self.stadium;
				
						
				return dictionary;
			}
		}
		
	