	
		//
		// PickDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class PickDTO 	    {
		 
				var id: Int?;
				    	 
		 
				var odd: Double?;
				    	 
		 
				var description: String?;
				    	 
		 
				var pickResult: PickResult?;
				    	 
		 
				var bookie: String?;
				    	 
		 
				var post_oid: [Int]?;
				    	 
		 
				var event_rel_oid: Int?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


				
					dictionary["id"] = self.id;
				

				
					dictionary["odd"] = self.odd;
				

				
					dictionary["description"] = self.description;
				

				
					dictionary["pickResult"] = self.pickResult?.rawValue;
				

				
					dictionary["bookie"] = self.bookie;
				

					dictionary["post_oid"] = self.post_oid;
			

					dictionary["event_rel_oid"] = self.event_rel_oid;
			
						
				return dictionary;
			}
		}
		
	