	
		//
		// PlayerDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class PlayerDTO 	    {
		 
				var club_team_oid: Int?;
				    	 
		 
				var national_team_oid: Int?;
				    	 
		 
				var id: Int?;
				    	 
		 
				var name: String?;
				    	 
		 
				var scorer_oid: [Int]?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


					dictionary["club_team_oid"] = self.club_team_oid;
			

					dictionary["national_team_oid"] = self.national_team_oid;
			

				
					dictionary["id"] = self.id;
				

				
					dictionary["name"] = self.name;
				

					dictionary["scorer_oid"] = self.scorer_oid;
			
						
				return dictionary;
			}
		}
		
	