	
		//
		// RequestDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class RequestDTO 	    {
		 
				var post_oid: Int?;
				    	 
		 
				var id: Int?;
				    	 
		 
				var type: RequestType?;
				    	 
		 
				var reason: String?;
				    	 
		 
				var state: RequestState?;
				    	 
		 
				var date: NSDate?;
				    	 
		 
				var adminComment: String?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


					dictionary["post_oid"] = self.post_oid;
			

				
					dictionary["id"] = self.id;
				

				
					dictionary["type"] = self.type?.rawValue;
				

				
					dictionary["reason"] = self.reason;
				

				
					dictionary["state"] = self.state?.rawValue;
				

				
					dictionary["date"] = self.date?.toString();
				

				
					dictionary["adminComment"] = self.adminComment;
				
						
				return dictionary;
			}
		}
		
	