	
		//
		// ResultDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class ResultDTO :    		PickDTO
	    {
		 
				var result: Result?;
				    	 
		 
				var matchtime: Time?;
				    	 
	   	   
			// MARK: - Constructor
			
			
			override init ()
			{
				super.init();
			}
			override func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
				dictionary = super.toDictionary();
			


				
					dictionary["result"] = self.result?.rawValue;
				

				
					dictionary["matchtime"] = self.matchtime?.rawValue;
				
						
				return dictionary;
			}
		}
		
	