	
		//
		// RoundDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class RoundDTO 	    {
		 
				var id: Int?;
				    	 
		 
				var season_oid: Int?;
				    	 
		 
				var event__oid: [Int]?;
				    	 
		 
				var name: String?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


				
					dictionary["id"] = self.id;
				

					dictionary["season_oid"] = self.season_oid;
			

					dictionary["event__oid"] = self.event__oid;
			

				
					dictionary["name"] = self.name;
				
						
				return dictionary;
			}
		}
		
	