	
		//
		// ScorerDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class ScorerDTO :    		PickDTO
	    {
		 
				var scorer_name: String?;
				    	 
		 
				var player_oid: Int?;
				    	 
	   	   
			// MARK: - Constructor
			
			
			override init ()
			{
				super.init();
			}
			override func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
				dictionary = super.toDictionary();
			


				
					dictionary["scorer_name"] = self.scorer_name;
				

					dictionary["player_oid"] = self.player_oid;
			
						
				return dictionary;
			}
		}
		
	