	
		//
		// SeasonDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class SeasonDTO 	    {
		 
				var id: Int?;
				    	 
		 
				var initDate: NSDate?;
				    	 
		 
				var finalDate: NSDate?;
				    	 
		 
				var competition_oid: Int?;
				    	 
		 
				var round_oid: [Int]?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


				
					dictionary["id"] = self.id;
				

				
					dictionary["initDate"] = self.initDate?.toString();
				

				
					dictionary["finalDate"] = self.finalDate?.toString();
				

					dictionary["competition_oid"] = self.competition_oid;
			

					dictionary["round_oid"] = self.round_oid;
			
						
				return dictionary;
			}
		}
		
	