	
		//
		// StatsDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class StatsDTO 	    {
		 
				var id: Int?;
				    	 
		 
				var benefit: Double?;
				    	 
		 
				var stakeAverage: Double?;
				    	 
		 
				var yield: Float?;
				    	 
		 
				var oddAverage: Double?;
				    	 
		 
				var totalPicks: Int?;
				    	 
		 
				var date: NSDate?;
				    	 
		 
				var tipster_oid: Int?;
				    	 
		 
				var oddAccumulator: Double?;
				    	 
		 
				var totalStaked: Double?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


				
					dictionary["id"] = self.id;
				

				
					dictionary["benefit"] = self.benefit;
				

				
					dictionary["stakeAverage"] = self.stakeAverage;
				

				
					dictionary["yield"] = self.yield;
				

				
					dictionary["oddAverage"] = self.oddAverage;
				

				
					dictionary["totalPicks"] = self.totalPicks;
				

				
					dictionary["date"] = self.date?.toString();
				

					dictionary["tipster_oid"] = self.tipster_oid;
			

				
					dictionary["oddAccumulator"] = self.oddAccumulator;
				

				
					dictionary["totalStaked"] = self.totalStaked;
				
						
				return dictionary;
			}
		}
		
	