	
		//
		// TeamDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class TeamDTO 	    {
		 
				var id: Int?;
				    	 
		 
				var name: String?;
				    	 
		 
				var country: String?;
				    	 
		 
				var event_home_oid: [Int]?;
				    	 
		 
				var event_away_oid: [Int]?;
				    	 
		 
				var club_player_oid: [Int]?;
				    	 
		 
				var national_player_oid: [Int]?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


				
					dictionary["id"] = self.id;
				

				
					dictionary["name"] = self.name;
				

				
					dictionary["country"] = self.country;
				

					dictionary["event_home_oid"] = self.event_home_oid;
			

					dictionary["event_away_oid"] = self.event_away_oid;
			

					dictionary["club_player_oid"] = self.club_player_oid;
			

					dictionary["national_player_oid"] = self.national_player_oid;
			
						
				return dictionary;
			}
		}
		
	