	
		//
		// UsuarioDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class UsuarioDTO 	    {
		 
				var id: Int?;
				    	 
		 
				var alias: String?;
				    	 
		 
				var email: String?;
				    	 
		 
				var password: String?;
				    	 
		 
				var created_at: NSDate?;
				    	 
		 
				var updated_at: NSDate?;
				    	 
		 
				var nif: String?;
				    	 
		 
				var admin: Bool?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


				
					dictionary["id"] = self.id;
				

				
					dictionary["alias"] = self.alias;
				

				
					dictionary["email"] = self.email;
				

				
					dictionary["password"] = self.password;
				

				
					dictionary["created_at"] = self.created_at?.toString();
				

				
					dictionary["updated_at"] = self.updated_at?.toString();
				

				
					dictionary["nif"] = self.nif;
				

				
					dictionary["admin"] = self.admin;
				
						
				return dictionary;
			}
		}
		
	