
package PickadosGenPickadosRESTAzure.uiModels.DTOA;

import PickadosGenPickadosRESTAzure.uiModels.DTO.*;
import PickadosGenPickadosRESTAzure.uiModels.DTO.utils.*;
import PickadosGenPickadosRESTAzure.uiModels.DTO.enumerations.*;

import java.util.ArrayList;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 * Code autogenerated. Do not modify this file.
 */
public class NationalTeamDTOA extends DTOA
{
	// region - Members, getters and setters

	
	private String name;
	public String getName () { return name; }
	public void setName (String name) { this.name = name; }
	
	private String country;
	public String getCountry () { return country; }
	public void setCountry (String country) { this.country = country; }
	
	private Integer id;
	public Integer getId () { return id; }
	public void setId (Integer id) { this.id = id; }
	
	
	/* Rol: NationalTeam o--> Player */
	private ArrayList<PlayerDTOA> getAllNational_playerOfNational_team;
	public ArrayList<PlayerDTOA> getGetAllNational_playerOfNational_team () { return getAllNational_playerOfNational_team; }
	public void setGetAllNational_playerOfNational_team (ArrayList<PlayerDTOA> getAllNational_playerOfNational_team) { this.getAllNational_playerOfNational_team = getAllNational_playerOfNational_team; }

	
	
	// endregion
	
	
	
	// region - Constructor and JSON <-> DTOA <-> DTO
	
	public NationalTeamDTOA ()
	{
		// Empty constructor
	}
	
	@Override
	public void setFromJSON (JSONObject json)
	{
		try
		{
			

			if (!JSONObject.NULL.equals(json.opt("Name")))
			{
			 
				this.name = (String) json.opt("Name");
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Country")))
			{
			 
				this.country = (String) json.opt("Country");
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Id")))
			{
			 
				this.id = (Integer) json.opt("Id");
			 
			}
			

			JSONObject jsonGetAllNational_playerOfNational_team = json.optJSONObject("GetAllNational_playerOfNational_team");
			if (jsonGetAllNational_playerOfNational_team != null)
			{
				PlayerDTOA tmp = new PlayerDTOA();
				tmp.setFromJSON(jsonGetAllNational_playerOfNational_team);
				this.getAllNational_playerOfNational_team = tmp;
			}

			
		}
		catch (Exception e)
		{
			e.printStackTrace();
		}
	}
	
	public JSONObject toJSON ()
	{
		JSONObject json = new JSONObject();
		
		try
		{
			
		
		  if (this.name != null)
			json.put("Name", this.name);
		
		
		  if (this.country != null)
			json.put("Country", this.country);
		
		
		  if (this.id != null)
			json.put("Id", this.id.intValue());
		
			

			if (this.getAllNational_playerOfNational_team != null)
			{
				json.put("GetAllNational_playerOfNational_team", this.getAllNational_playerOfNational_team.toJSON());
			}

			
		}
		catch (JSONException e)
		{
			e.printStackTrace();
		}
		
		return json;
	}
	
	@Override 
	public IDTO toDTO ()
	{
		TeamDTO dto = new TeamDTO ();
		
		// Attributes
		
		
	dto.setName (this.getName());

	dto.setCountry (this.getCountry());

	dto.setId (this.getId());

		
		
		// Roles
					// TODO: from DTOA [ GetAllNational_playerOfNational_team ] (dataType : ArrayList<PlayerDTOA>) to DTO [ National_player ]
		
		
		return dto;
	}

	// endregion
}

	