
package PickadosGenPickadosRESTAzure.uiModels.DTOA;

import PickadosGenPickadosRESTAzure.uiModels.DTO.*;
import PickadosGenPickadosRESTAzure.uiModels.DTO.utils.*;
import PickadosGenPickadosRESTAzure.uiModels.DTO.enumerations.*;

import java.util.ArrayList;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 * Code autogenerated. Do not modify this file.
 */
public class PostDTOA extends DTOA
{
	// region - Members, getters and setters

	private Integer id;
	public Integer getId () { return id; }
	public void setId (Integer id) { this.id = id; }

	
	private Double stake;
	public Double getStake () { return stake; }
	public void setStake (Double stake) { this.stake = stake; }
	
	private String description;
	public String getDescription () { return description; }
	public void setDescription (String description) { this.description = description; }
	
	private Double totalOdd;
	public Double getTotalOdd () { return totalOdd; }
	public void setTotalOdd (Double totalOdd) { this.totalOdd = totalOdd; }
	
	
	
	
	// endregion
	
	
	
	// region - Constructor and JSON <-> DTOA <-> DTO
	
	public PostDTOA ()
	{
		// Empty constructor
	}
	
	@Override
	public void setFromJSON (JSONObject json)
	{
		try
		{
			if (!JSONObject.NULL.equals(json.opt("Id")))
			{
				this.id = (Integer) json.opt("Id");
			}
			

			if (!JSONObject.NULL.equals(json.opt("Stake")))
			{
			 
			 	String stringDouble = String.valueOf(json.opt("Stake"));
 				this.stake = Double.parseDouble(stringDouble);
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Description")))
			{
			 
				this.description = (String) json.opt("Description");
			 
			}

			if (!JSONObject.NULL.equals(json.opt("TotalOdd")))
			{
			 
			 	String stringDouble = String.valueOf(json.opt("TotalOdd"));
 				this.totalOdd = Double.parseDouble(stringDouble);
			 
			}
			
			
		}
		catch (Exception e)
		{
			e.printStackTrace();
		}
	}
	
	public JSONObject toJSON ()
	{
		JSONObject json = new JSONObject();
		
		try
		{
			if (this.id != null){
				json.put("Id", this.id);
			}
			
		
		  if (this.stake != null)
			json.put("Stake", this.stake);
		
		
		  if (this.description != null)
			json.put("Description", this.description);
		
		
		  if (this.totalOdd != null)
			json.put("TotalOdd", this.totalOdd);
		
			
			
		}
		catch (JSONException e)
		{
			e.printStackTrace();
		}
		
		return json;
	}
	
	@Override 
	public IDTO toDTO ()
	{
		PostDTO dto = new PostDTO ();
		
		// Attributes
		
	dto.setId (this.getId());

		
	dto.setStake (this.getStake());

	dto.setDescription (this.getDescription());

	dto.setTotalOdd (this.getTotalOdd());

		
		
		// Roles
		
		
		return dto;
	}

	// endregion
}

	