//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminView.App_Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class properties_spa {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal properties_spa() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdminView.App_Resources.properties_spa", typeof(properties_spa).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mes/Año.
        /// </summary>
        public static string login_stat_axisx {
            get {
                return ResourceManager.GetString("login_stat_axisx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total conexiones.
        /// </summary>
        public static string login_stat_axisy {
            get {
                return ResourceManager.GetString("login_stat_axisy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a theme2.
        /// </summary>
        public static string login_stat_theme {
            get {
                return ResourceManager.GetString("login_stat_theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Control de conexiones.
        /// </summary>
        public static string login_stat_title {
            get {
                return ResourceManager.GetString("login_stat_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a column.
        /// </summary>
        public static string login_stat_type {
            get {
                return ResourceManager.GetString("login_stat_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mes/Año.
        /// </summary>
        public static string post_stat_axisx {
            get {
                return ResourceManager.GetString("post_stat_axisx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total post.
        /// </summary>
        public static string post_stat_axisy {
            get {
                return ResourceManager.GetString("post_stat_axisy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a theme2.
        /// </summary>
        public static string post_stat_theme {
            get {
                return ResourceManager.GetString("post_stat_theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Control de publicaciones.
        /// </summary>
        public static string post_stat_title {
            get {
                return ResourceManager.GetString("post_stat_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a column.
        /// </summary>
        public static string post_stat_type {
            get {
                return ResourceManager.GetString("post_stat_type", resourceCulture);
            }
        }
    }
}
