	
		package PickadosGenPickadosRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  PickadosGenPickadosRESTAzure.uiModels.DTO.utils.*;
		import  PickadosGenPickadosRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class CompetitionDTO 	    implements IDTO
	    {
				private Integer id;
				public Integer getId () { return id; } 
				public void setId  (Integer value) { id = value;  } 
				    	 
				private String name;
				public String getName () { return name; } 
				public void setName  (String value) { name = value;  } 
				    	 
				private ArrayList<Event_DTO> event_;
				public ArrayList<Event_DTO> getEvent_ () { return event_; } 
				public void setEvent_ (ArrayList<Event_DTO> value) { event_ = value;  } 
				    	 
				private Integer sport_oid;
				public Integer  getSport_oid () { return sport_oid; } 
				public void setSport_oid (Integer value) { sport_oid = value;  } 
				    	 
				private String place;
				public String getPlace () { return place; } 
				public void setPlace  (String value) { place = value;  } 
				    	 
				private ArrayList<Integer> team_oid;
				public ArrayList<Integer>  getTeam_oid () { return team_oid; } 
				public void setTeam_oid (ArrayList<Integer> value) { team_oid = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{
				
						  json.put("Id", this.id.intValue());
				
				
						  json.put("Name", this.name);
				

						if (this.event_ != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.event_.size(); ++i)
							{
								jsonArray.put(this.event_.get(i).toJSON());
							}
							json.put("Event_", jsonArray);
						}

						if (this.sport_oid != null)
						{
							json.put("Sport_oid", this.sport_oid.intValue());
						}
				
						  json.put("Place", this.place);
				

						if (this.team_oid != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.team_oid.size(); ++i)
							{
								jsonArray.put(this.team_oid.get(i));
							}
							json.put("Team_oid", jsonArray);
						}
		
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	