	
		package PickadosGenPickadosRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  PickadosGenPickadosRESTAzure.uiModels.DTO.utils.*;
		import  PickadosGenPickadosRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class CorrectScoreDTO extends    		PickDTO
	    implements IDTO
	    {
				private Integer homeScore;
				public Integer getHomeScore () { return homeScore; } 
				public void setHomeScore  (Integer value) { homeScore = value;  } 
				    	 
				private Integer awayScore;
				public Integer getAwayScore () { return awayScore; } 
				public void setAwayScore  (Integer value) { awayScore = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{
				
						  json.put("HomeScore", this.homeScore.intValue());
				
				
						  json.put("AwayScore", this.awayScore.intValue());
				
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	