	
		package PickadosGenPickadosRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  PickadosGenPickadosRESTAzure.uiModels.DTO.utils.*;
		import  PickadosGenPickadosRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class Event_DTO 	    implements IDTO
	    {
				private Integer id;
				public Integer getId () { return id; } 
				public void setId  (Integer value) { id = value;  } 
				    	 
				private Integer competition_oid;
				public Integer  getCompetition_oid () { return competition_oid; } 
				public void setCompetition_oid (Integer value) { competition_oid = value;  } 
				    	 
				private ArrayList<PickDTO> pick_rel;
				public ArrayList<PickDTO> getPick_rel () { return pick_rel; } 
				public void setPick_rel (ArrayList<PickDTO> value) { pick_rel = value;  } 
				    	 
				private java.util.Date date;
				public java.util.Date getDate () { return date; } 
				public void setDate  (java.util.Date value) { date = value;  } 
				    	 
				private Integer round_oid;
				public Integer  getRound_oid () { return round_oid; } 
				public void setRound_oid (Integer value) { round_oid = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{
				
						  json.put("Id", this.id.intValue());
				

						if (this.competition_oid != null)
						{
							json.put("Competition_oid", this.competition_oid.intValue());
						}

						if (this.pick_rel != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.pick_rel.size(); ++i)
							{
								jsonArray.put(this.pick_rel.get(i).toJSON());
							}
							json.put("Pick_rel", jsonArray);
						}
				
						  json.put("Date", DateUtils.dateToFormatString(this.date));
				

						if (this.round_oid != null)
						{
							json.put("Round_oid", this.round_oid.intValue());
						}
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	