	
		package PickadosGenPickadosRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  PickadosGenPickadosRESTAzure.uiModels.DTO.utils.*;
		import  PickadosGenPickadosRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class MatchDTO extends    		Event_DTO
	    implements IDTO
	    {
				private Integer away_oid;
				public Integer  getAway_oid () { return away_oid; } 
				public void setAway_oid (Integer value) { away_oid = value;  } 
				    	 
				private Integer home_oid;
				public Integer  getHome_oid () { return home_oid; } 
				public void setHome_oid (Integer value) { home_oid = value;  } 
				    	 
				private String stadium;
				public String getStadium () { return stadium; } 
				public void setStadium  (String value) { stadium = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{

						if (this.away_oid != null)
						{
							json.put("Away_oid", this.away_oid.intValue());
						}

						if (this.home_oid != null)
						{
							json.put("Home_oid", this.home_oid.intValue());
						}
				
						  json.put("Stadium", this.stadium);
				
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	