	
		package PickadosGenPickadosRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  PickadosGenPickadosRESTAzure.uiModels.DTO.utils.*;
		import  PickadosGenPickadosRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class PickDTO 	    implements IDTO
	    {
				private Integer id;
				public Integer getId () { return id; } 
				public void setId  (Integer value) { id = value;  } 
				    	 
				private Double odd;
				public Double getOdd () { return odd; } 
				public void setOdd  (Double value) { odd = value;  } 
				    	 
				private String description;
				public String getDescription () { return description; } 
				public void setDescription  (String value) { description = value;  } 
				    	 
				private PickResult pickResult;
				public PickResult getPickResult () { return pickResult; } 
				public void setPickResult  (PickResult value) { pickResult = value;  } 
				    	 
				private String bookie;
				public String getBookie () { return bookie; } 
				public void setBookie  (String value) { bookie = value;  } 
				    	 
				private ArrayList<Integer> post_oid;
				public ArrayList<Integer>  getPost_oid () { return post_oid; } 
				public void setPost_oid (ArrayList<Integer> value) { post_oid = value;  } 
				    	 
				private Integer event_rel_oid;
				public Integer  getEvent_rel_oid () { return event_rel_oid; } 
				public void setEvent_rel_oid (Integer value) { event_rel_oid = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{
				
						  json.put("Id", this.id.intValue());
				
				
						  json.put("Odd", this.odd);
				
				
						  json.put("Description", this.description);
				
				
						  json.put("PickResult", this.pickResult.getRawValue());
				
				
						  json.put("Bookie", this.bookie);
				

						if (this.post_oid != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.post_oid.size(); ++i)
							{
								jsonArray.put(this.post_oid.get(i));
							}
							json.put("Post_oid", jsonArray);
						}
		

						if (this.event_rel_oid != null)
						{
							json.put("Event_rel_oid", this.event_rel_oid.intValue());
						}
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	