	
		package PickadosGenPickadosRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  PickadosGenPickadosRESTAzure.uiModels.DTO.utils.*;
		import  PickadosGenPickadosRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class PostDTO 	    implements IDTO
	    {
				private Integer id;
				public Integer getId () { return id; } 
				public void setId  (Integer value) { id = value;  } 
				    	 
				private java.util.Date created_at;
				public java.util.Date getCreated_at () { return created_at; } 
				public void setCreated_at  (java.util.Date value) { created_at = value;  } 
				    	 
				private java.util.Date modified_at;
				public java.util.Date getModified_at () { return modified_at; } 
				public void setModified_at  (java.util.Date value) { modified_at = value;  } 
				    	 
				private Double stake;
				public Double getStake () { return stake; } 
				public void setStake  (Double value) { stake = value;  } 
				    	 
				private String description;
				public String getDescription () { return description; } 
				public void setDescription  (String value) { description = value;  } 
				    	 
				private Boolean private_;
				public Boolean getPrivate_ () { return private_; } 
				public void setPrivate_  (Boolean value) { private_ = value;  } 
				    	 
				private ArrayList<Integer> pick_oid;
				public ArrayList<Integer>  getPick_oid () { return pick_oid; } 
				public void setPick_oid (ArrayList<Integer> value) { pick_oid = value;  } 
				    	 
				private Integer tipster_oid;
				public Integer  getTipster_oid () { return tipster_oid; } 
				public void setTipster_oid (Integer value) { tipster_oid = value;  } 
				    	 
				private Double totalOdd;
				public Double getTotalOdd () { return totalOdd; } 
				public void setTotalOdd  (Double value) { totalOdd = value;  } 
				    	 
				private PickResult postResult;
				public PickResult getPostResult () { return postResult; } 
				public void setPostResult  (PickResult value) { postResult = value;  } 
				    	 
				private ArrayList<Integer> request_oid;
				public ArrayList<Integer>  getRequest_oid () { return request_oid; } 
				public void setRequest_oid (ArrayList<Integer> value) { request_oid = value;  } 
				    	 
				private Integer likeit;
				public Integer getLikeit () { return likeit; } 
				public void setLikeit  (Integer value) { likeit = value;  } 
				    	 
				private Integer report;
				public Integer getReport () { return report; } 
				public void setReport  (Integer value) { report = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{
				
						  json.put("Id", this.id.intValue());
				
				
						  json.put("Created_at", DateUtils.dateToFormatString(this.created_at));
				
				
						  json.put("Modified_at", DateUtils.dateToFormatString(this.modified_at));
				
				
						  json.put("Stake", this.stake);
				
				
						  json.put("Description", this.description);
				
				
						  json.put("Private_", this.private_);
				

						if (this.pick_oid != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.pick_oid.size(); ++i)
							{
								jsonArray.put(this.pick_oid.get(i));
							}
							json.put("Pick_oid", jsonArray);
						}
		

						if (this.tipster_oid != null)
						{
							json.put("Tipster_oid", this.tipster_oid.intValue());
						}
				
						  json.put("TotalOdd", this.totalOdd);
				
				
						  json.put("PostResult", this.postResult.getRawValue());
				

						if (this.request_oid != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.request_oid.size(); ++i)
							{
								jsonArray.put(this.request_oid.get(i));
							}
							json.put("Request_oid", jsonArray);
						}
		
				
						  json.put("Likeit", this.likeit.intValue());
				
				
						  json.put("Report", this.report.intValue());
				
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	