	
		package PickadosGenPickadosRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  PickadosGenPickadosRESTAzure.uiModels.DTO.utils.*;
		import  PickadosGenPickadosRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class RoundDTO 	    implements IDTO
	    {
				private Integer id;
				public Integer getId () { return id; } 
				public void setId  (Integer value) { id = value;  } 
				    	 
				private Integer season_oid;
				public Integer  getSeason_oid () { return season_oid; } 
				public void setSeason_oid (Integer value) { season_oid = value;  } 
				    	 
				private ArrayList<Integer> event__oid;
				public ArrayList<Integer>  getEvent__oid () { return event__oid; } 
				public void setEvent__oid (ArrayList<Integer> value) { event__oid = value;  } 
				    	 
				private String name;
				public String getName () { return name; } 
				public void setName  (String value) { name = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{
				
						  json.put("Id", this.id.intValue());
				

						if (this.season_oid != null)
						{
							json.put("Season_oid", this.season_oid.intValue());
						}

						if (this.event__oid != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.event__oid.size(); ++i)
							{
								jsonArray.put(this.event__oid.get(i));
							}
							json.put("Event__oid", jsonArray);
						}
		
				
						  json.put("Name", this.name);
				
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	