	
		package PickadosGenPickadosRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  PickadosGenPickadosRESTAzure.uiModels.DTO.utils.*;
		import  PickadosGenPickadosRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class ScorerDTO extends    		PickDTO
	    implements IDTO
	    {
				private String scorer_name;
				public String getScorer_name () { return scorer_name; } 
				public void setScorer_name  (String value) { scorer_name = value;  } 
				    	 
				private Integer player_oid;
				public Integer  getPlayer_oid () { return player_oid; } 
				public void setPlayer_oid (Integer value) { player_oid = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{
				
						  json.put("Scorer_name", this.scorer_name);
				

						if (this.player_oid != null)
						{
							json.put("Player_oid", this.player_oid.intValue());
						}
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	