	
		package PickadosGenPickadosRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  PickadosGenPickadosRESTAzure.uiModels.DTO.utils.*;
		import  PickadosGenPickadosRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class SeasonDTO 	    implements IDTO
	    {
				private Integer id;
				public Integer getId () { return id; } 
				public void setId  (Integer value) { id = value;  } 
				    	 
				private java.util.Date initDate;
				public java.util.Date getInitDate () { return initDate; } 
				public void setInitDate  (java.util.Date value) { initDate = value;  } 
				    	 
				private java.util.Date finalDate;
				public java.util.Date getFinalDate () { return finalDate; } 
				public void setFinalDate  (java.util.Date value) { finalDate = value;  } 
				    	 
				private Integer competition_oid;
				public Integer  getCompetition_oid () { return competition_oid; } 
				public void setCompetition_oid (Integer value) { competition_oid = value;  } 
				    	 
				private ArrayList<Integer> round_oid;
				public ArrayList<Integer>  getRound_oid () { return round_oid; } 
				public void setRound_oid (ArrayList<Integer> value) { round_oid = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{
				
						  json.put("Id", this.id.intValue());
				
				
						  json.put("InitDate", DateUtils.dateToFormatString(this.initDate));
				
				
						  json.put("FinalDate", DateUtils.dateToFormatString(this.finalDate));
				

						if (this.competition_oid != null)
						{
							json.put("Competition_oid", this.competition_oid.intValue());
						}

						if (this.round_oid != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.round_oid.size(); ++i)
							{
								jsonArray.put(this.round_oid.get(i));
							}
							json.put("Round_oid", jsonArray);
						}
		
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	