	
		package PickadosGenPickadosRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  PickadosGenPickadosRESTAzure.uiModels.DTO.utils.*;
		import  PickadosGenPickadosRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class SportDTO 	    implements IDTO
	    {
				private ArrayList<CompetitionDTO> competition;
				public ArrayList<CompetitionDTO> getCompetition () { return competition; } 
				public void setCompetition (ArrayList<CompetitionDTO> value) { competition = value;  } 
				    	 
				private Integer id;
				public Integer getId () { return id; } 
				public void setId  (Integer value) { id = value;  } 
				    	 
				private String name;
				public String getName () { return name; } 
				public void setName  (String value) { name = value;  } 
				    	 
				private ArrayList<Integer> player_oid;
				public ArrayList<Integer>  getPlayer_oid () { return player_oid; } 
				public void setPlayer_oid (ArrayList<Integer> value) { player_oid = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{

						if (this.competition != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.competition.size(); ++i)
							{
								jsonArray.put(this.competition.get(i).toJSON());
							}
							json.put("Competition", jsonArray);
						}
				
						  json.put("Id", this.id.intValue());
				
				
						  json.put("Name", this.name);
				

						if (this.player_oid != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.player_oid.size(); ++i)
							{
								jsonArray.put(this.player_oid.get(i));
							}
							json.put("Player_oid", jsonArray);
						}
		
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	