	
		package PickadosGenPickadosRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  PickadosGenPickadosRESTAzure.uiModels.DTO.utils.*;
		import  PickadosGenPickadosRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class StatsDTO 	    implements IDTO
	    {
				private Integer id;
				public Integer getId () { return id; } 
				public void setId  (Integer value) { id = value;  } 
				    	 
				private Double benefit;
				public Double getBenefit () { return benefit; } 
				public void setBenefit  (Double value) { benefit = value;  } 
				    	 
				private Double stakeAverage;
				public Double getStakeAverage () { return stakeAverage; } 
				public void setStakeAverage  (Double value) { stakeAverage = value;  } 
				    	 
				private float yield;
				public float getYield () { return yield; } 
				public void setYield  (float value) { yield = value;  } 
				    	 
				private Double oddAverage;
				public Double getOddAverage () { return oddAverage; } 
				public void setOddAverage  (Double value) { oddAverage = value;  } 
				    	 
				private Integer totalPicks;
				public Integer getTotalPicks () { return totalPicks; } 
				public void setTotalPicks  (Integer value) { totalPicks = value;  } 
				    	 
				private java.util.Date initialDate;
				public java.util.Date getInitialDate () { return initialDate; } 
				public void setInitialDate  (java.util.Date value) { initialDate = value;  } 
				    	 
				private Integer tipster_oid;
				public Integer  getTipster_oid () { return tipster_oid; } 
				public void setTipster_oid (Integer value) { tipster_oid = value;  } 
				    	 
				private Double oddAccumulator;
				public Double getOddAccumulator () { return oddAccumulator; } 
				public void setOddAccumulator  (Double value) { oddAccumulator = value;  } 
				    	 
				private Double totalStaked;
				public Double getTotalStaked () { return totalStaked; } 
				public void setTotalStaked  (Double value) { totalStaked = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{
				
						  json.put("Id", this.id.intValue());
				
				
						  json.put("Benefit", this.benefit);
				
				
						  json.put("StakeAverage", this.stakeAverage);
				
				
						  json.put("Yield", this.yield);
				
				
						  json.put("OddAverage", this.oddAverage);
				
				
						  json.put("TotalPicks", this.totalPicks.intValue());
				
				
						  json.put("InitialDate", DateUtils.dateToFormatString(this.initialDate));
				

						if (this.tipster_oid != null)
						{
							json.put("Tipster_oid", this.tipster_oid.intValue());
						}
				
						  json.put("OddAccumulator", this.oddAccumulator);
				
				
						  json.put("TotalStaked", this.totalStaked);
				
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	