	
		package PickadosGenPickadosRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  PickadosGenPickadosRESTAzure.uiModels.DTO.utils.*;
		import  PickadosGenPickadosRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class TeamDTO 	    implements IDTO
	    {
				private Integer id;
				public Integer getId () { return id; } 
				public void setId  (Integer value) { id = value;  } 
				    	 
				private String name;
				public String getName () { return name; } 
				public void setName  (String value) { name = value;  } 
				    	 
				private String country;
				public String getCountry () { return country; } 
				public void setCountry  (String value) { country = value;  } 
				    	 
				private ArrayList<Integer> event_home_oid;
				public ArrayList<Integer>  getEvent_home_oid () { return event_home_oid; } 
				public void setEvent_home_oid (ArrayList<Integer> value) { event_home_oid = value;  } 
				    	 
				private ArrayList<Integer> event_away_oid;
				public ArrayList<Integer>  getEvent_away_oid () { return event_away_oid; } 
				public void setEvent_away_oid (ArrayList<Integer> value) { event_away_oid = value;  } 
				    	 
				private ArrayList<Integer> club_player_oid;
				public ArrayList<Integer>  getClub_player_oid () { return club_player_oid; } 
				public void setClub_player_oid (ArrayList<Integer> value) { club_player_oid = value;  } 
				    	 
				private ArrayList<Integer> national_player_oid;
				public ArrayList<Integer>  getNational_player_oid () { return national_player_oid; } 
				public void setNational_player_oid (ArrayList<Integer> value) { national_player_oid = value;  } 
				    	 
				private ArrayList<Integer> competition_oid;
				public ArrayList<Integer>  getCompetition_oid () { return competition_oid; } 
				public void setCompetition_oid (ArrayList<Integer> value) { competition_oid = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{
				
						  json.put("Id", this.id.intValue());
				
				
						  json.put("Name", this.name);
				
				
						  json.put("Country", this.country);
				

						if (this.event_home_oid != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.event_home_oid.size(); ++i)
							{
								jsonArray.put(this.event_home_oid.get(i));
							}
							json.put("Event_home_oid", jsonArray);
						}
		

						if (this.event_away_oid != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.event_away_oid.size(); ++i)
							{
								jsonArray.put(this.event_away_oid.get(i));
							}
							json.put("Event_away_oid", jsonArray);
						}
		

						if (this.club_player_oid != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.club_player_oid.size(); ++i)
							{
								jsonArray.put(this.club_player_oid.get(i));
							}
							json.put("Club_player_oid", jsonArray);
						}
		

						if (this.national_player_oid != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.national_player_oid.size(); ++i)
							{
								jsonArray.put(this.national_player_oid.get(i));
							}
							json.put("National_player_oid", jsonArray);
						}
		

						if (this.competition_oid != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.competition_oid.size(); ++i)
							{
								jsonArray.put(this.competition_oid.get(i));
							}
							json.put("Competition_oid", jsonArray);
						}
		
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	