	
		package PickadosGenPickadosRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  PickadosGenPickadosRESTAzure.uiModels.DTO.utils.*;
		import  PickadosGenPickadosRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class TipsterDTO extends    		UsuarioDTO
	    implements IDTO
	    {
				private ArrayList<StatsDTO> monthlyStats;
				public ArrayList<StatsDTO> getMonthlyStats () { return monthlyStats; } 
				public void setMonthlyStats (ArrayList<StatsDTO> value) { monthlyStats = value;  } 
				    	 
				private ArrayList<PostDTO> post;
				public ArrayList<PostDTO> getPost () { return post; } 
				public void setPost (ArrayList<PostDTO> value) { post = value;  } 
				    	 
				private ArrayList<Integer> follow_to_oid;
				public ArrayList<Integer>  getFollow_to_oid () { return follow_to_oid; } 
				public void setFollow_to_oid (ArrayList<Integer> value) { follow_to_oid = value;  } 
				    	 
				private ArrayList<Integer> followed_by_oid;
				public ArrayList<Integer>  getFollowed_by_oid () { return followed_by_oid; } 
				public void setFollowed_by_oid (ArrayList<Integer> value) { followed_by_oid = value;  } 
				    	 
				private Boolean premium;
				public Boolean getPremium () { return premium; } 
				public void setPremium  (Boolean value) { premium = value;  } 
				    	 
				private Double subscription_fee;
				public Double getSubscription_fee () { return subscription_fee; } 
				public void setSubscription_fee  (Double value) { subscription_fee = value;  } 
				    	 
				private Boolean locked;
				public Boolean getLocked () { return locked; } 
				public void setLocked  (Boolean value) { locked = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{

						if (this.monthlyStats != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.monthlyStats.size(); ++i)
							{
								jsonArray.put(this.monthlyStats.get(i).toJSON());
							}
							json.put("MonthlyStats", jsonArray);
						}

						if (this.post != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.post.size(); ++i)
							{
								jsonArray.put(this.post.get(i).toJSON());
							}
							json.put("Post", jsonArray);
						}

						if (this.follow_to_oid != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.follow_to_oid.size(); ++i)
							{
								jsonArray.put(this.follow_to_oid.get(i));
							}
							json.put("Follow_to_oid", jsonArray);
						}
		

						if (this.followed_by_oid != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.followed_by_oid.size(); ++i)
							{
								jsonArray.put(this.followed_by_oid.get(i));
							}
							json.put("Followed_by_oid", jsonArray);
						}
		
				
						  json.put("Premium", this.premium);
				
				
						  json.put("Subscription_fee", this.subscription_fee);
				
				
						  json.put("Locked", this.locked);
				
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	