	
		package PickadosGenPickadosRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  PickadosGenPickadosRESTAzure.uiModels.DTO.utils.*;
		import  PickadosGenPickadosRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class UsuarioDTO 	    implements IDTO
	    {
				private Integer id;
				public Integer getId () { return id; } 
				public void setId  (Integer value) { id = value;  } 
				    	 
				private String alias;
				public String getAlias () { return alias; } 
				public void setAlias  (String value) { alias = value;  } 
				    	 
				private String email;
				public String getEmail () { return email; } 
				public void setEmail  (String value) { email = value;  } 
				    	 
				private String password;
				public String getPassword () { return password; } 
				public void setPassword  (String value) { password = value;  } 
				    	 
				private java.util.Date created_at;
				public java.util.Date getCreated_at () { return created_at; } 
				public void setCreated_at  (java.util.Date value) { created_at = value;  } 
				    	 
				private java.util.Date updated_at;
				public java.util.Date getUpdated_at () { return updated_at; } 
				public void setUpdated_at  (java.util.Date value) { updated_at = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{
				
						  json.put("Id", this.id.intValue());
				
				
						  json.put("Alias", this.alias);
				
				
						  json.put("Email", this.email);
				
				
						  json.put("Password", this.password);
				
				
						  json.put("Created_at", DateUtils.dateToFormatString(this.created_at));
				
				
						  json.put("Updated_at", DateUtils.dateToFormatString(this.updated_at));
				
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	