//
// ClubTeamsDTOA.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation
import SwiftyJSON
		
class ClubTeamsDTOA : DTOA
{
	// MARK: - Properties

	
	var name: String?;
	var country: String?;
	var id: Int?;
	
	/* Rol: ClubTeams o--> Player */
	var getAllClub_playerOfClub_team: [PlayerDTOA]?;

	
	
	
	
	// MARK: - Constructor
	
	init ()
	{
		// Empty constructor
	}
	
	
	
	// MARK: - JSON <-> DTOA
	
	required init (fromJSONObject json: JSON)
	{
		
	
		self.name = json["Name"].object as? String;
		self.country = json["Country"].object as? String;
		self.id = json["Id"].object as? Int;
		
		if (json["GetAllClub_playerOfClub_team"] != JSON.null)
		{
			self.getAllClub_playerOfClub_team = PlayerDTOA(fromJSONObject: json["GetAllClub_playerOfClub_team"]);
		}

		
	}
	
	func toDictionary() -> [String : AnyObject]
	{
		var dictionary: [String : AnyObject] = [:];
		
		
	

	
		dictionary["Name"] = self.name;
	
	

	
		dictionary["Country"] = self.country;
	
	

	
		dictionary["Id"] = self.id;
	
	
		
		dictionary["GetAllClub_playerOfClub_team"] = self.getAllClub_playerOfClub_team?.toDictionary() ?? NSNull();

		
		
		return dictionary;
	}
}

	