//
// MatchDTOA.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation
import SwiftyJSON
		
class MatchDTOA : DTOA
{
	// MARK: - Properties

	
	var date: NSDate?;
	var stadium: String?;
	var id: Int?;
	
	/* Rol: Match o--> Team */
	var getHomeOfEvent_home: TeamDTOA?;

	/* Rol: Match o--> Team */
	var getAwayOfEvent_away: TeamDTOA?;

	
	
	
	
	// MARK: - Constructor
	
	init ()
	{
		// Empty constructor
	}
	
	
	
	// MARK: - JSON <-> DTOA
	
	required init (fromJSONObject json: JSON)
	{
		
	
	
		self.date = NSDate.initFromString(json["Date"].object as? String);
		self.stadium = json["Stadium"].object as? String;
		self.id = json["Id"].object as? Int;
		
		if (json["GetHomeOfEvent_home"] != JSON.null)
		{
			self.getHomeOfEvent_home = TeamDTOA(fromJSONObject: json["GetHomeOfEvent_home"]);
		}

		if (json["GetAwayOfEvent_away"] != JSON.null)
		{
			self.getAwayOfEvent_away = TeamDTOA(fromJSONObject: json["GetAwayOfEvent_away"]);
		}

		
	}
	
	func toDictionary() -> [String : AnyObject]
	{
		var dictionary: [String : AnyObject] = [:];
		
		
	

	
		dictionary["Date"] = self.date?.toString();
	
	

	
		dictionary["Stadium"] = self.stadium;
	
	

	
		dictionary["Id"] = self.id;
	
	
		
		dictionary["GetHomeOfEvent_home"] = self.getHomeOfEvent_home?.toDictionary() ?? NSNull();

		dictionary["GetAwayOfEvent_away"] = self.getAwayOfEvent_away?.toDictionary() ?? NSNull();

		
		
		return dictionary;
	}
}

	