//
// MatchDTOA.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation
import SwiftyJSON
		
class MatchDTOA : DTOA
{
	// MARK: - Properties

	var id: Int?;
	
	var stadium: String?;
	var date: NSDate?;
	
	
	
	
	
	// MARK: - Constructor
	
	init ()
	{
		// Empty constructor
	}
	
	
	
	// MARK: - JSON <-> DTOA
	
	required init (fromJSONObject json: JSON)
	{
		self.id = json["Id"].object as? Int
		
	
		self.stadium = json["Stadium"].object as? String;
	
		self.date = NSDate.initFromString(json["Date"].object as? String);
		
		
	}
	
	func toDictionary() -> [String : AnyObject]
	{
		var dictionary: [String : AnyObject] = [:];
		
		dictionary["Id"] = self.id;
		
	

	
		dictionary["Stadium"] = self.stadium;
	
	

	
		dictionary["Date"] = self.date?.toString();
	
	
		
		
		
		return dictionary;
	}
}

	