//
// NationalTeamDTOA.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation
import SwiftyJSON
		
class NationalTeamDTOA : DTOA
{
	// MARK: - Properties

	
	var name: String?;
	var country: String?;
	var id: Int?;
	
	/* Rol: NationalTeam o--> Player */
	var getAllNational_playerOfNational_team: [PlayerDTOA]?;

	
	
	
	
	// MARK: - Constructor
	
	init ()
	{
		// Empty constructor
	}
	
	
	
	// MARK: - JSON <-> DTOA
	
	required init (fromJSONObject json: JSON)
	{
		
	
		self.name = json["Name"].object as? String;
		self.country = json["Country"].object as? String;
		self.id = json["Id"].object as? Int;
		
		if (json["GetAllNational_playerOfNational_team"] != JSON.null)
		{
			self.getAllNational_playerOfNational_team = PlayerDTOA(fromJSONObject: json["GetAllNational_playerOfNational_team"]);
		}

		
	}
	
	func toDictionary() -> [String : AnyObject]
	{
		var dictionary: [String : AnyObject] = [:];
		
		
	

	
		dictionary["Name"] = self.name;
	
	

	
		dictionary["Country"] = self.country;
	
	

	
		dictionary["Id"] = self.id;
	
	
		
		dictionary["GetAllNational_playerOfNational_team"] = self.getAllNational_playerOfNational_team?.toDictionary() ?? NSNull();

		
		
		return dictionary;
	}
}

	