//
// PickDTOA.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation
import SwiftyJSON
		
class PickDTOA : DTOA
{
	// MARK: - Properties

	var id: Int?;
	
	var odd: Double?;
	var pickResult: PickResult?;
	var bookie: String?;
	
	
	
	
	
	// MARK: - Constructor
	
	init ()
	{
		// Empty constructor
	}
	
	
	
	// MARK: - JSON <-> DTOA
	
	required init (fromJSONObject json: JSON)
	{
		self.id = json["Id"].object as? Int
		
	
		self.odd = json["Odd"].object as? Double;
		if let enumValue = json["PickResult"].object as? Int
		{
			self.pickResult = PickResult(rawValue: enumValue);
		}
		self.bookie = json["Bookie"].object as? String;
		
		
	}
	
	func toDictionary() -> [String : AnyObject]
	{
		var dictionary: [String : AnyObject] = [:];
		
		dictionary["Id"] = self.id;
		
	

	
		dictionary["Odd"] = self.odd;
	
	

	
		dictionary["PickResult"] = self.pickResult?.rawValue;
	
	

	
		dictionary["Bookie"] = self.bookie;
	
	
		
		
		
		return dictionary;
	}
}

	