//
// RequestDTOA.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation
import SwiftyJSON
		
class RequestDTOA : DTOA
{
	// MARK: - Properties

	
	var type: RequestType?;
	var id: Int?;
	var reason: String?;
	var state: RequestState?;
	var date: NSDate?;
	
	
	
	
	
	// MARK: - Constructor
	
	init ()
	{
		// Empty constructor
	}
	
	
	
	// MARK: - JSON <-> DTOA
	
	required init (fromJSONObject json: JSON)
	{
		
	
		if let enumValue = json["Type"].object as? Int
		{
			self.type = RequestType(rawValue: enumValue);
		}
		self.id = json["Id"].object as? Int;
		self.reason = json["Reason"].object as? String;
		if let enumValue = json["State"].object as? Int
		{
			self.state = RequestState(rawValue: enumValue);
		}
	
		self.date = NSDate.initFromString(json["Date"].object as? String);
		
		
	}
	
	func toDictionary() -> [String : AnyObject]
	{
		var dictionary: [String : AnyObject] = [:];
		
		
	

	
		dictionary["Type"] = self.type?.rawValue;
	
	

	
		dictionary["Id"] = self.id;
	
	

	
		dictionary["Reason"] = self.reason;
	
	

	
		dictionary["State"] = self.state?.rawValue;
	
	

	
		dictionary["Date"] = self.date?.toString();
	
	
		
		
		
		return dictionary;
	}
}

	