//
// SportDTOA.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation
import SwiftyJSON
		
class SportDTOA : DTOA
{
	// MARK: - Properties

	var id: Int?;
	
	var name: String?;
	
	/* Rol: Sport o--> Competition */
	var getAllCompetitionOfSport: [CompetitionDTOA]?;

	
	
	
	
	// MARK: - Constructor
	
	init ()
	{
		// Empty constructor
	}
	
	
	
	// MARK: - JSON <-> DTOA
	
	required init (fromJSONObject json: JSON)
	{
		self.id = json["Id"].object as? Int
		
	
		self.name = json["Name"].object as? String;
		
		if (json["GetAllCompetitionOfSport"] != JSON.null)
		{
			self.getAllCompetitionOfSport = CompetitionDTOA(fromJSONObject: json["GetAllCompetitionOfSport"]);
		}

		
	}
	
	func toDictionary() -> [String : AnyObject]
	{
		var dictionary: [String : AnyObject] = [:];
		
		dictionary["Id"] = self.id;
		
	

	
		dictionary["Name"] = self.name;
	
	
		
		dictionary["GetAllCompetitionOfSport"] = self.getAllCompetitionOfSport?.toDictionary() ?? NSNull();

		
		
		return dictionary;
	}
}

	