//
// SportDTOA.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation
import SwiftyJSON
		
class SportDTOA : DTOA
{
	// MARK: - Properties

	var id: Int?;
	
	var name: String?;
	
	/* GetAll: Competition */
	var getAllCompetition: [CompetitionDTOA]?;

	
	
	
	
	// MARK: - Constructor
	
	init ()
	{
		// Empty constructor
	}
	
	
	
	// MARK: - JSON <-> DTOA
	
	required init (fromJSONObject json: JSON)
	{
		self.id = json["Id"].object as? Int
		
	
		self.name = json["Name"].object as? String;
		
		if (json["GetAllCompetition"] != JSON.null)
		{
			self.getAllCompetition = [];
			for subJson in json["GetAllCompetition"].arrayValue
			{
				self.getAllCompetition!.append(CompetitionDTOA(fromJSONObject: subJson));
			}
		}

		
	}
	
	func toDictionary() -> [String : AnyObject]
	{
		var dictionary: [String : AnyObject] = [:];
		
		dictionary["Id"] = self.id;
		
	

	
		dictionary["Name"] = self.name;
	
	
		
		dictionary["GetAllCompetition"] = NSNull();
		if (self.getAllCompetition != nil)
		{
			var arrayOfDictionary: [[String : AnyObject]] = [];
			for item in self.getAllCompetition!
			{
				arrayOfDictionary.append(item.toDictionary());
			}
			
			dictionary["GetAllCompetition"] = arrayOfDictionary;
		}

		
		
		return dictionary;
	}
}

	