//
// TipsterStatsDTOA.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation
import SwiftyJSON
		
class TipsterStatsDTOA : DTOA
{
	// MARK: - Properties

	var id: Int?;
	
	var alias: String?;
	var subscription_fee: Double?;
	var premium: Bool?;
	
	/* Rol: TipsterStats o--> Stats */
	var getStatsOfTipster: [StatsDTOA]?;

	
	
	
	
	// MARK: - Constructor
	
	init ()
	{
		// Empty constructor
	}
	
	
	
	// MARK: - JSON <-> DTOA
	
	required init (fromJSONObject json: JSON)
	{
		self.id = json["Id"].object as? Int
		
	
		self.alias = json["Alias"].object as? String;
		self.subscription_fee = json["Subscription_fee"].object as? Double;
		self.premium = json["Premium"].object as? Bool;
		
		if (json["GetStatsOfTipster"] != JSON.null)
		{
			self.getStatsOfTipster = [];
			for subJson in json["GetStatsOfTipster"].arrayValue
			{
				self.getStatsOfTipster!.append(StatsDTOA(fromJSONObject: subJson));
			}
		}

		
	}
	
	func toDictionary() -> [String : AnyObject]
	{
		var dictionary: [String : AnyObject] = [:];
		
		dictionary["Id"] = self.id;
		
	

	
		dictionary["Alias"] = self.alias;
	
	

	
		dictionary["Subscription_fee"] = self.subscription_fee;
	
	

	
		dictionary["Premium"] = self.premium;
	
	
		
		dictionary["GetStatsOfTipster"] = NSNull();
		if (self.getStatsOfTipster != nil)
		{
			var arrayOfDictionary: [[String : AnyObject]] = [];
			for item in self.getStatsOfTipster!
			{
				arrayOfDictionary.append(item.toDictionary());
			}
			
			dictionary["GetStatsOfTipster"] = arrayOfDictionary;
		}

		
		
		return dictionary;
	}
}

	