//
// UsuarioDTOA.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation
import SwiftyJSON
		
class UsuarioDTOA : DTOA
{
	// MARK: - Properties

	var id: Int?;
	
	var nif: String?;
	var email: String?;
	var alias: String?;
	
	
	
	
	
	// MARK: - Constructor
	
	init ()
	{
		// Empty constructor
	}
	
	
	
	// MARK: - JSON <-> DTOA
	
	required init (fromJSONObject json: JSON)
	{
		self.id = json["Id"].object as? Int
		
	
		self.nif = json["Nif"].object as? String;
		self.email = json["Email"].object as? String;
		self.alias = json["Alias"].object as? String;
		
		
	}
	
	func toDictionary() -> [String : AnyObject]
	{
		var dictionary: [String : AnyObject] = [:];
		
		dictionary["Id"] = self.id;
		
	

	
		dictionary["Nif"] = self.nif;
	
	

	
		dictionary["Email"] = self.email;
	
	

	
		dictionary["Alias"] = self.alias;
	
	
		
		
		
		return dictionary;
	}
}

	