
package PickadosGenPickadosRESTAzure.uiModels.DTO.enumerations;

/**
 * Code autogenerated. Do not modify this file.
 */
public enum Meses
{
	// region - Literals

	January (1)
	,	February (2)
	,	March (3)
	,	April (4)
	,	May (5)
	,	June (6)
	,	July (7)
	,	August (8)
	,	September (9)
	,	October (10)
	,	November (11)
	,	December (12)
;

	// endregion


	// region - Members and constructor

	private final int rawValue;

	public int getRawValue ()
	{
		return this.rawValue;
	}

	Meses (int rawValue)
	{
		this.rawValue = rawValue;
	}

	// endregion


	// region - Public methods

	public static Meses fromRawValue (int rawValue)
	{
		Meses[] enumValues = Meses.values();

		for (int i = 0; i < enumValues.length; i++)
		{
			if (enumValues[i].Compare(rawValue))
			{
				return enumValues[i];
			}
		}

		return null;
	}

	public boolean Compare (int rawValue)
	{
		return this.rawValue == rawValue;
	}

	// endregion
	
}
